### ISSUE TITLE
ValueError: numpy.dtype does not appear to be the correct type object 에러 문제 해결

### ISSUE THREAD

**Issue by swzoey** [kookmin-sw/2018-cap1-7#20]
Traceback (most recent call last):
  File "ceps_based_classifier.py", line 19, in <module>
    from ceps import read_ceps
  File "/Users/zoey/workspace/capstone/lab/code/ceps.py", line 15, in <module>
    from scikits.talkbox.features import mfcc
  File "/Library/Python/2.7/site-packages/scikits/talkbox/__init__.py", line 3, in <module>
    from tools import *
  File "/Library/Python/2.7/site-packages/scikits/talkbox/tools/__init__.py", line 7, in <module>
    import cffilter
  File "numpy.pxd", line 30, in cffilter (scikits/talkbox/tools/src/cffilter.c:2795)
ValueError: numpy.dtype does not appear to be the correct type object

**Comment by swzoey** [comment]
pip install --upgrade --force-reinstall scikits.talkbox
