### ISSUE TITLE
라즈베리파이에서  ceps_based_classifier.py 실행 오류

### ISSUE THREAD

**Issue by swzoey** [kookmin-sw/2018-cap1-7#52]
/home/viewtiful/.local/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "ceps_based_classifier.py", line 125, in <module>
    create_model, X, y, "Log Reg CEPS", plot=True)
  File "ceps_based_classifier.py", line 31, in train_model
    n=len(X), n_iter=1, test_size=0.3, indices=True, random_state=0)
TypeError: __init__() got an unexpected keyword argument 'indices'

**Comment by swzoey** [comment]
Traceback (most recent call last):
  File "main.py", line 142, in <module>
    create_model, X, y, "Log Reg CEPS", plot=True)
  File "main.py", line 54, in train_model
    clf.fit(X_train, y_train)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.py", line 665, in fit
    raise ValueError("The number of classes has to be greater than"
ValueError: The number of classes has to be greater than one.

**Comment by swzoey** [comment]
특정 소리 파일(ceps.npy )문제와 파이썬 모듈 버전 문제로 인해 발생
소리파일 변경과 모듈 down-grade로 문제해결
